name: Unzip Project

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip project files
        run: |
          mkdir app
          unzip anti_tamper_repo_update.zip -d app

      - name: Commit unzipped files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add app
          git commit -m "Unzipped project files"
          git push
